openapi: 3.0.0
info:
  title: Swagger study
  description: I'm studying!
  contact:
    name: Itaru Furukawa
    email: hzk.seventh.heaven@me.com
  version: 1.0.0
servers:
- url: /swagger-test/v1/
tags:
- name: users
  description: Access to Users
- name: producets
  description: Access to Products
paths:
  /users:
    get:
      tags:
      - users
      summary: Get all users.
      description: Return users
      operationId: usersGET
      parameters: []
      responses:
        "200":
          description: OK!
          content:
            application/json:
              schema:
                type: array
                example:
                - id: 1
                  name: John Doe
                - id: 2
                  name: Itaru
                items:
                  $ref: '#/components/schemas/User'
                x-content-type: application/json
      x-swagger-router-controller: Users
    post:
      tags:
      - users
      summary: Create a new user
      description: create a new user
      operationId: usersPOST
      parameters: []
      requestBody:
        description: user to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
            - id: 3
              name: Kanami
      responses:
        "201":
          description: CREATED
      x-swagger-router-controller: Users
  /users/{userId}:
    get:
      tags:
      - users
      summary: Get user by ID
      description: Return a single User
      operationId: usersUserIdGET
      parameters:
      - name: userId
        in: path
        description: user id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Ok!
          content:
            application/json:
              schema:
                type: array
                example:
                  id: 1
                  name: John Doe
                items:
                  $ref: '#/components/schemas/User'
                x-content-type: application/json
      x-swagger-router-controller: Users
components:
  schemas:
    User:
      required:
      - id
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Product:
      required:
      - id
      - price
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Laptop
        price:
          type: integer
          example: 1200
